services:
  docs:
    image: bitpin_local_docs
    container_name: bitpin_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./bitpin:/app/bitpin:z
    ports:
      - '9000:9000'
    command: /start-docs
